wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1649070118
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 19
      4: 3.8.8
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 100
embedding_dims:
  desc: null
  value: 10
epochs:
  desc: null
  value: 10
filters:
  desc: null
  value: 16
hidden_dims:
  desc: null
  value: 250
maxlen:
  desc: null
  value: 1000
vocab_size:
  desc: null
  value: 10000
